05-20 14:16:02 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO INSTRUCTOR(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('1','1','1','1','none')INSERT[*] INTO INSTRUCTOR(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('ali','ali','ali','','eng')INSERT INTO INSTRUCTOR(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('armin','armin','armin','armin','farsi')INSERT INTO INSTRUCTOR(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('mohammad','mohammad','mohammad','mohammadi','arabic')INSERT INTO INSTRUCTOR(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('jajeem','jajeem','jajeem','jajeem','none')INSERT INTO STUDENT(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('2','2','2','2','none')INSERT INTO STUDENT(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('ali','ali','ali','ali','none')INSERT INTO STUDENT(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('master','master','master','master','none')INSERT INTO STUDENT(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,LANGUAGE) VALUES('student','student','student','student','none')INSERT INTO ROOM(NAME,SEATSIZE) VALUES('a',10)INSERT INTO ROOM(NAME,SEATSIZE) VALUES('b',20)INSERT INTO ROOM(NAME,SEATSIZE) VALUES('c',30)INSERT INTO ROOM(NAME,SEATSIZE) VALUES('d',45)INSERT INTO COURSE(NAME) VALUES('farsi')INSERT INTO COURSE(NAME) VALUES('english')INSERT INTO COURSE(NAME) VALUES('math')INSERT INTO COURSE(NAME) VALUES('physic')INSERT INTO COURSE(NAME) VALUES('chemistry')INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a1',1,1)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a2',2,1)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a3',3,1)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a4',4,1)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a5',1,2)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a6',1,3)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a7',1,4)INSERT INTO SEAT(ROOMID,NAME,ROW,COL) VALUES(2,'a8',1,5) "; SQL statement:
Insert into instructor(username,password,firstname,lastname,language) values('1','1','1','1','none')Insert into instructor(username,password,firstname,lastname,language) values('ali','ali','ali','','eng')Insert into instructor(username,password,firstname,lastname,language) values('armin','armin','armin','armin','farsi')Insert into instructor(username,password,firstname,lastname,language) values('mohammad','mohammad','mohammad','mohammadi','arabic')Insert into instructor(username,password,firstname,lastname,language) values('jajeem','jajeem','jajeem','jajeem','none')Insert into student(username,password,firstname,lastname,language) values('2','2','2','2','none')Insert into student(username,password,firstname,lastname,language) values('ali','ali','ali','ali','none')Insert into student(username,password,firstname,lastname,language) values('master','master','master','master','none')Insert into student(username,password,firstname,lastname,language) values('student','student','student','student','none')Insert into room(name,seatsize) values('a',10)Insert into room(name,seatsize) values('b',20)Insert into room(name,seatsize) values('c',30)Insert into room(name,seatsize) values('d',45)Insert into course(name) values('farsi')Insert into course(name) values('english')Insert into course(name) values('math')Insert into course(name) values('physic')Insert into course(name) values('chemistry')Insert into seat(roomid,name,row,col) values(2,'a1',1,1)Insert into seat(roomid,name,row,col) values(2,'a2',2,1)Insert into seat(roomid,name,row,col) values(2,'a3',3,1)Insert into seat(roomid,name,row,col) values(2,'a4',4,1)Insert into seat(roomid,name,row,col) values(2,'a5',1,2)Insert into seat(roomid,name,row,col) values(2,'a6',1,3)Insert into seat(roomid,name,row,col) values(2,'a7',1,4)Insert into seat(roomid,name,row,col) values(2,'a8',1,5) [42000-171]
05-20 14:35:30 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 14:36:29 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 14:36:45 jdbc[4]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 14:40:34 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 14:41:09 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 14:54:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 14:54:19 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 15:02:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 15:05:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 16:12:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 16:19:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 16:19:17 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 16:25:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 16:25:14 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-20 16:26:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Insert into room(name,seatsize) values('a',10);Insert into room(name,seatsize) values('b',20);Insert into room(name,seatsize) values('c',30);Insert into room(name,seatsize) values('d',45);Insert into course(name) values('farsi');Insert into course(name) values('english');Insert into course(name) values('math');Insert into course(name) values('physic');Insert into course(name) values('chemistry');Insert into seat(roomid,name,row,col) values(2,'a1',1,1);Insert into seat(roomid,name,row,col) values(2,'a2',2,1);Insert into seat(roomid,name,row,col) values(2,'a3',3,1);Insert into seat(roomid,name,row,col) values(2,'a4',4,1);Insert into seat(roomid,name,row,col) values(2,'a5',1,2);Insert into seat(roomid,name,row,col) values(2,'a6',1,3);Insert into seat(roomid,name,row,col) values(2,'a7',1,4);Insert into seat(roomid,name,row,col) values(2,'a8',1,5); [42122-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:607)
	at org.h2.command.Parser.parseColumn(Parser.java:801)
	at org.h2.command.Parser.parseColumnList(Parser.java:786)
	at org.h2.command.Parser.parseInsert(Parser.java:974)
	at org.h2.command.Parser.parsePrepared(Parser.java:374)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:417)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:32)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:42)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:84)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.main(Instructor.java:49)
05-20 16:26:39 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:25)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 21 more
05-21 15:12:01 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.util.initDatabase.initialize(initDatabase.java:12)
	at com.jajeem.util.StartUp.<init>(StartUp.java:15)
	at com.jajeem.core.design.Instructor.<init>(Instructor.java:70)
	at com.jajeem.core.design.Instructor$1.run(Instructor.java:52)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 34 more
05-21 15:57:21 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-21 15:57:21 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:30:17 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:30:17 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:39:13 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:39:13 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:50:12 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:50:12 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:53:37 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 12:53:37 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 13:01:12 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 13:01:12 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 13:09:46 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
05-22 13:09:46 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:73)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	at com.jajeem.util.ConnectionManager.getConnection(ConnectionManager.java:49)
	at com.jajeem.util.Connection.getConnection(Connection.java:19)
	at com.jajeem.util.BaseDAO.getConnection(BaseDAO.java:14)
	at com.jajeem.core.dao.h2.StudentDAO.authenticate(StudentDAO.java:31)
	at com.jajeem.core.service.StudentService.authenticate(StudentService.java:15)
	at com.jajeem.command.handler.SetAuthenticateCommandHanlder.run(SetAuthenticateCommandHanlder.java:28)
	at com.jajeem.command.service.ClientService.process(ClientService.java:182)
	at com.jajeem.command.service.ClientService.run(ClientService.java:84)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 22 more
